name: Build and push Docker image
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Variables
              run: |
                  echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
                  echo IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7) >> $GITHUB_ENV
            - name: "Create db directory"
              run: mkdir data
            - name: "Create env file"
              run: |
                  touch .env
                  echo DB_PATH="./data/database.db" >> .env
                  cat .env
            - name: Log in to ghcr.io
              run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Build and tag image
              run: |
                  docker build . -t ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} -t ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
            - name: Push image to GHCR
              run: docker push ghcr.io/${{ env.IMAGE_REPOSITORY }} --all-tags
